In [1]:
import numpy as np

In [2]:
a=np.array([0,1,2])

In [21]:
print(a)

[0 1 2]


In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
print(a.shape)

(3,)


In [5]:
print(a[0])

0


In [10]:
print(a.ndim)

1


In [6]:
#Creating a 2 dimensional array
b=np.array([[0,1,2],[3,4,5]])

In [7]:
print(b.shape)

(2, 3)


In [8]:
print(b)

[[0 1 2]
 [3 4 5]]


In [9]:
print(b.ndim)

2


In [17]:
d=np.array((((1,2),(3,4)),((5,6),(7,8))))

In [18]:
print(d.ndim)

3


In [19]:
print(d.shape)

(2, 2, 2)


In [20]:
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [23]:
np.full((1,3),2)

array([[2, 2, 2]])

In [24]:
np.linspace(2,4,3)

array([2., 3., 4.])

In [26]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [28]:
np.linspace(0,10,2)

array([ 0., 10.])

In [29]:
e=np.eye(3)

In [30]:
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
e.ravel()

array([1., 0., 0., 0., 1., 0., 0., 0., 1.])

In [33]:
ar1=np.zeros((2,2))

In [34]:
ar1

array([[0., 0.],
       [0., 0.]])

In [35]:
ar2=np.ones((2,2))

In [36]:
ar2

array([[1., 1.],
       [1., 1.]])

In [39]:
ar3=np.hstack((ar1,ar2))

In [40]:
ar3

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [41]:
ar4=np.concatenate((ar1,ar2),axis=1)

In [42]:
ar4

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [43]:
x=np.array([5,6,7,8,9])

In [44]:
x[1:7:2]

array([6, 8])

In [45]:
y = np.array([[[1],[2],[3]], [[4],[5],[6]]])
y

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [46]:
y[1:3]

array([[[4],
        [5],
        [6]]])

In [47]:
y.shape

(2, 3, 1)

In [48]:
# Create a rank 2 array with shape (3, 4)
a = np.array([[5,6,7,8], [1,2,3,4], [9,10,11,12]])
print ("Array a:", a)

Array a: [[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]


In [49]:
b = a[:2, 1:3]
print ("Array b:", b)

Array b: [[6 7]
 [2 3]]


In [50]:
# create a matrix
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
# create a vector
v = np.array([1, 0, 1])

In [51]:
# Create an empty matrix with the same shape as a
b = np.empty_like(a)

In [52]:
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
v

array([1, 0, 1])

In [54]:
b=a+v
b

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10]])

In [55]:
d=a+1

In [56]:
d

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [57]:
import pandas as pd

# Sample DataFrame
data = {
    'A': [4, 1, 3, 2],
    'B': [7, 11, 9, 6],
    'C': [10, 2, 5, 8]
}
df = pd.DataFrame(data)

# Sorting by column 'A' in ascending order
sorted_df = df.sort_values(by='A')
print(sorted_df)


   A   B   C
1  1  11   2
3  2   6   8
2  3   9   5
0  4   7  10


In [58]:
# Sorting by column 'B' in descending order
sorted_desc_df = df.sort_values(by='B', ascending=False)
print(sorted_desc_df)



   A   B   C
1  1  11   2
2  3   9   5
0  4   7  10
3  2   6   8


In [59]:
# Sorting the DataFrame by index in ascending order
sorted_index_df = df.sort_index()
print(sorted_index_df)


   A   B   C
0  4   7  10
1  1  11   2
2  3   9   5
3  2   6   8


In [60]:
df

A   B   C
0  4   7  10
1  1  11   2
2  3   9   5
3  2   6   8

In [61]:
# Sorting the DataFrame by index in descending order
sorted_desc_index_df = df.sort_index(ascending=False)
print(sorted_desc_index_df)


   A   B   C
3  2   6   8
2  3   9   5
1  1  11   2
0  4   7  10


In [63]:
# Multi-level sorting by columns 'A' and 'B'
multi_sorted_df = df.sort_values(by=['A', 'C'])
print(multi_sorted_df)


   A   B   C
1  1  11   2
3  2   6   8
2  3   9   5
0  4   7  10


In [64]:
print (df.iloc[1,1])

11


In [65]:
import pandas as pd

# Creating a sample DataFrame
data = {
    'Category': ['A', 'B', 'A', 'B', 'A'],
    'Value': [10, 20, 30, 40, 50]
}
df = pd.DataFrame(data)

# Grouping by 'Category' and applying aggregation
result = df.groupby('Category').agg({'Value': ['sum', 'mean', 'min', 'max']})
print(result)


         Value              
           sum  mean min max
Category                    
A           90  30.0  10  50
B           60  30.0  20  40
