In [1]:
import numpy as np

In [2]:
a=np.array([0,1,2])

In [21]:
print(a)

[0 1 2]


In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
print(a.shape)

(3,)


In [5]:
print(a[0])

0


In [10]:
print(a.ndim)

1


In [6]:
#Creating a 2 dimensional array
b=np.array([[0,1,2],[3,4,5]])

In [7]:
print(b.shape)

(2, 3)


In [8]:
print(b)

[[0 1 2]
 [3 4 5]]


In [9]:
print(b.ndim)

2


In [17]:
d=np.array((((1,2),(3,4)),((5,6),(7,8))))

In [18]:
print(d.ndim)

3


In [19]:
print(d.shape)

(2, 2, 2)


In [20]:
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [23]:
np.full((1,3),2)

array([[2, 2, 2]])

In [24]:
np.linspace(2,4,3)

array([2., 3., 4.])

In [26]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [28]:
np.linspace(0,10,2)

array([ 0., 10.])

In [29]:
e=np.eye(3)

In [30]:
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
e.ravel()

array([1., 0., 0., 0., 1., 0., 0., 0., 1.])

In [33]:
ar1=np.zeros((2,2))

In [34]:
ar1

array([[0., 0.],
       [0., 0.]])

In [35]:
ar2=np.ones((2,2))

In [36]:
ar2

array([[1., 1.],
       [1., 1.]])

In [39]:
ar3=np.hstack((ar1,ar2))

In [40]:
ar3

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [41]:
ar4=np.concatenate((ar1,ar2),axis=1)

In [42]:
ar4

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [43]:
x=np.array([5,6,7,8,9])

In [44]:
x[1:7:2]

array([6, 8])

In [45]:
y = np.array([[[1],[2],[3]], [[4],[5],[6]]])
y

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [46]:
y[1:3]

array([[[4],
        [5],
        [6]]])

In [47]:
y.shape

(2, 3, 1)

In [48]:
# Create a rank 2 array with shape (3, 4)
a = np.array([[5,6,7,8], [1,2,3,4], [9,10,11,12]])
print ("Array a:", a)

Array a: [[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]


In [49]:
b = a[:2, 1:3]
print ("Array b:", b)

Array b: [[6 7]
 [2 3]]


In [50]:
# create a matrix
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
# create a vector
v = np.array([1, 0, 1])

In [51]:
# Create an empty matrix with the same shape as a
b = np.empty_like(a)

In [52]:
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
v

array([1, 0, 1])

In [54]:
b=a+v
b

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10]])

In [55]:
d=a+1

In [56]:
d

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [57]:
import pandas as pd

# Sample DataFrame
data = {
    'A': [4, 1, 3, 2],
    'B': [7, 11, 9, 6],
    'C': [10, 2, 5, 8]
}
df = pd.DataFrame(data)

# Sorting by column 'A' in ascending order
sorted_df = df.sort_values(by='A')
print(sorted_df)


   A   B   C
1  1  11   2
3  2   6   8
2  3   9   5
0  4   7  10


In [58]:
# Sorting by column 'B' in descending order
sorted_desc_df = df.sort_values(by='B', ascending=False)
print(sorted_desc_df)



   A   B   C
1  1  11   2
2  3   9   5
0  4   7  10
3  2   6   8


In [59]:
# Sorting the DataFrame by index in ascending order
sorted_index_df = df.sort_index()
print(sorted_index_df)


   A   B   C
0  4   7  10
1  1  11   2
2  3   9   5
3  2   6   8


In [60]:
df

A   B   C
0  4   7  10
1  1  11   2
2  3   9   5
3  2   6   8

In [61]:
# Sorting the DataFrame by index in descending order
sorted_desc_index_df = df.sort_index(ascending=False)
print(sorted_desc_index_df)


   A   B   C
3  2   6   8
2  3   9   5
1  1  11   2
0  4   7  10


In [63]:
# Multi-level sorting by columns 'A' and 'B'
multi_sorted_df = df.sort_values(by=['A', 'C'])
print(multi_sorted_df)


   A   B   C
1  1  11   2
3  2   6   8
2  3   9   5
0  4   7  10


In [64]:
print (df.iloc[1,1])

11


In [65]:
import pandas as pd

# Creating a sample DataFrame
data = {
    'Category': ['A', 'B', 'A', 'B', 'A'],
    'Value': [10, 20, 30, 40, 50]
}
df = pd.DataFrame(data)

# Grouping by 'Category' and applying aggregation
result = df.groupby('Category').agg({'Value': ['sum', 'mean', 'min', 'max']})
print(result)


         Value              
           sum  mean min max
Category                    
A           90  30.0  10  50
B           60  30.0  20  40


In [1]:
import category_encoders as ce
import pandas as pd
data=pd.DataFrame({'City':[
'Delhi','Mumbai','Hydrabad','Chennai','Bangalore','Delhi','Hydrabad','Bangalore','Delhi'
]})

#Create object for one-hot encoding
encoder=ce.OneHotEncoder(cols='City',handle_unknown='return_nan',return_df=True,use_cat_names=True)

#Original Data
data

City
0      Delhi
1     Mumbai
2   Hydrabad
3    Chennai
4  Bangalore
5      Delhi
6   Hydrabad
7  Bangalore
8      Delhi

In [2]:
#Fit and transform Data
data_encoded = encoder.fit_transform(data)
data_encoded

City_Delhi  City_Mumbai  City_Hydrabad  City_Chennai  City_Bangalore
0         1.0          0.0            0.0           0.0             0.0
1         0.0          1.0            0.0           0.0             0.0
2         0.0          0.0            1.0           0.0             0.0
3         0.0          0.0            0.0           1.0             0.0
4         0.0          0.0            0.0           0.0             1.0
5         1.0          0.0            0.0           0.0             0.0
6         0.0          0.0            1.0           0.0             0.0
7         0.0          0.0            0.0           0.0             1.0
8         1.0          0.0            0.0           0.0             0.0

In [7]:
#encode the data
data_encoded=pd.get_dummies(data=data,drop_first=True)
data_encoded

City_Chennai  City_Delhi  City_Hyderabad  City_Mumbai
0         False        True           False        False
1         False       False           False         True
2         False       False            True        False
3          True       False           False        False
4         False       False           False        False
5         False        True           False        False

In [10]:
#effect encoding
data

City
0      Delhi
1     Mumbai
2  Hyderabad
3    Chennai
4  Bangalore
5      Delhi

In [11]:
encoder.fit_transform(data)

City_Delhi  City_Mumbai  City_Hyderabad  City_Chennai  City_Bangalore
0         1.0          0.0             0.0           0.0             0.0
1         0.0          1.0             0.0           0.0             0.0
2         0.0          0.0             1.0           0.0             0.0
3         0.0          0.0             0.0           1.0             0.0
4         0.0          0.0             0.0           0.0             1.0
5         1.0          0.0             0.0           0.0             0.0

In [13]:
#hashing encoding
import category_encoders as ce
import pandas as pd

#Create the dataframe
data=pd.DataFrame({'Month':['January','April','March','April','Februay','June','July','June','September']})
print(data)
#Create object for hash encoder
encoder=ce.HashingEncoder(cols='Month',n_components=6)

       Month
0    January
1      April
2      March
3      April
4    Februay
5       June
6       July
7       June
8  September


In [14]:
#Fit and Transform Data
encoder.fit_transform(data)

col_0  col_1  col_2  col_3  col_4  col_5
0      0      0      0      0      1      0
1      0      0      0      1      0      0
2      0      0      0      0      1      0
3      0      0      0      1      0      0
4      0      0      0      1      0      0
5      0      1      0      0      0      0
6      1      0      0      0      0      0
7      0      1      0      0      0      0
8      0      0      0      0      1      0

In [15]:
#Import the libraries
import category_encoders as ce
import pandas as pd

#Create the dataframe
data=pd.DataFrame({'City':['Delhi','Mumbai','Hyderabad','Chennai','Bangalore','Delhi','Hyderabad','Mumbai','Agra']})

#Create an object for Base N Encoding
encoder= ce.BaseNEncoder(cols=['city'],return_df=True,base=5)

#Original Data
data

City
0      Delhi
1     Mumbai
2  Hyderabad
3    Chennai
4  Bangalore
5      Delhi
6  Hyderabad
7     Mumbai
8       Agra

In [18]:
#import the libraries
import pandas as pd
import category_encoders as ce

#Create the Dataframe
Data=pd.DataFrame({'class':['A,','B','C','B','C','A','A','A'],'Marks':[50,30,70,80,45,97,80,68]})

#Create target encoding object
encoder=ce.TargetEncoder(cols='class') 

#Original Data
Data

class  Marks
0    A,     50
1     B     30
2     C     70
3     B     80
4     C     45
5     A     97
6     A     80
7     A     68

In [19]:
#Fit and Transform Train Data
encoder.fit_transform(data['class'],data['Marks'])

class
0  63.048373
1  63.581489
2  63.936117
3  63.581489
4  63.936117
5  67.574421
6  67.574421
7  67.574421